import { Schema, model, type HydratedDocument, type InferSchemaType } from 'mongoose';

export const MESSAGE_TYPES = ['text', 'voice', 'image', 'system'] as const;
export type MessageType = (typeof MESSAGE_TYPES)[number];

// The file behind a voice/image message. The file itself is on disk (uploads/<key>) and is only
// ever served through GET /api/media/:messageId, which checks conversation membership.
const mediaSchema = new Schema(
  {
    key: { type: String, required: true }, // e.g. "images/2026/09/<uuid>.webp"
    mimeType: { type: String, required: true },
    size: { type: Number, required: true }, // bytes
    durationMs: { type: Number }, // voice
    waveform: { type: [Number], default: undefined }, // voice: ~48 bars, each 0..1
    width: { type: Number }, // image
    height: { type: Number }, // image
  },
  { _id: false },
);

// Group events shown as small centered lines ("Jay added Ana"). Names are snapshotted so the line
// still reads right after someone leaves or renames themselves.
export const SYSTEM_EVENTS = ['created', 'added', 'removed', 'left', 'renamed', 'role'] as const;
export type SystemEventKind = (typeof SYSTEM_EVENTS)[number];

const personRefSchema = new Schema(
  { id: { type: Schema.Types.ObjectId, required: true }, name: { type: String, required: true } },
  { _id: false },
);

const systemEventSchema = new Schema(
  {
    kind: { type: String, enum: SYSTEM_EVENTS, required: true },
    actor: { type: personRefSchema, required: true },
    targets: { type: [personRefSchema], default: undefined },
    name: { type: String }, // created / renamed: the group name
    role: { type: String }, // role: the new role
  },
  { _id: false },
);

// One reaction per person per message (reacting again replaces it).
const reactionSchema = new Schema(
  {
    emoji: { type: String, required: true, maxlength: 16 },
    user: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  },
  { _id: false },
);

// Snapshot of the message being replied to, so history loads without extra lookups.
// Kept in sync when the original is edited or unsent.
const replySnapshotSchema = new Schema(
  {
    messageId: { type: Schema.Types.ObjectId, required: true },
    sender: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    type: { type: String, required: true },
    preview: { type: String, default: '' },
    deleted: { type: Boolean, default: false },
  },
  { _id: false },
);

const messageSchema = new Schema(
  {
    conversation: { type: Schema.Types.ObjectId, ref: 'Conversation', required: true },
    sender: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    type: { type: String, enum: MESSAGE_TYPES, default: 'text' },
    text: { type: String, trim: true, maxlength: 4000, default: '' }, // message, or photo caption
    media: { type: mediaSchema, default: null },
    system: { type: systemEventSchema, default: null }, // type 'system' only
    replyTo: { type: replySnapshotSchema, default: null },
    reactions: { type: [reactionSchema], default: [] },
    // Random id generated by the sender's device. Lets the client match its optimistic bubble to the
    // saved message, and makes retries safe: sending the same clientId twice never creates a duplicate.
    clientId: { type: String, maxlength: 64 },
    editedAt: { type: Date, default: null },
    deletedAt: { type: Date, default: null },
  },
  { timestamps: true },
);

// History pagination: newest first within a conversation (ObjectIds sort by creation time).
messageSchema.index({ conversation: 1, _id: -1 });
messageSchema.index({ 'replyTo.messageId': 1 }, { partialFilterExpression: { replyTo: { $type: 'object' } } });
messageSchema.index({ sender: 1, clientId: 1 }, { unique: true, partialFilterExpression: { clientId: { $type: 'string' } } });

export type MessageDoc = HydratedDocument<InferSchemaType<typeof messageSchema>>;

export const Message = model('Message', messageSchema);

export function toPublicMessage(m: MessageDoc) {
  const id = m._id.toString();
  const media =
    m.media && !m.deletedAt
      ? {
          url: `/api/media/${id}`,
          mimeType: m.media.mimeType,
          size: m.media.size,
          durationMs: m.media.durationMs ?? null,
          waveform: m.media.waveform ?? null,
          width: m.media.width ?? null,
          height: m.media.height ?? null,
        }
      : null;

  return {
    id,
    conversationId: m.conversation.toString(),
    senderId: m.sender.toString(),
    type: m.type,
    text: m.deletedAt ? '' : m.text,
    media,
    system: m.system
      ? {
          kind: m.system.kind,
          actor: { id: m.system.actor.id.toString(), name: m.system.actor.name },
          targets: (m.system.targets ?? []).map((t) => ({ id: t.id.toString(), name: t.name })),
          name: m.system.name ?? null,
          role: m.system.role ?? null,
        }
      : null,
    replyTo: m.replyTo
      ? {
          id: m.replyTo.messageId.toString(),
          senderId: m.replyTo.sender.toString(),
          type: m.replyTo.type,
          preview: m.replyTo.deleted ? '' : m.replyTo.preview,
          deleted: m.replyTo.deleted,
        }
      : null,
    reactions: summarizeReactions(m.deletedAt ? [] : m.reactions),
    clientId: m.clientId ?? null,
    createdAt: m.createdAt,
    editedAt: m.editedAt ?? null,
    deletedAt: m.deletedAt ?? null,
  };
}

export type PublicMessage = ReturnType<typeof toPublicMessage>;

// [{emoji:'❤️',user:a},{emoji:'❤️',user:b},{emoji:'👍',user:c}] -> [{emoji:'❤️',count:2,userIds:[a,b]}, …]
function summarizeReactions(reactions: { emoji: string; user: { toString(): string } }[]) {
  const byEmoji = new Map<string, string[]>();
  for (const r of reactions) byEmoji.set(r.emoji, [...(byEmoji.get(r.emoji) ?? []), r.user.toString()]);
  return [...byEmoji].map(([emoji, userIds]) => ({ emoji, count: userIds.length, userIds }));
}

export const EDIT_WINDOW_MS = 15 * 60 * 1000;
export const DELETED_PREVIEW = 'This message was deleted';

// Short text for the chat list and notifications.
export function previewFor(type: string, text: string): string {
  if (type === 'voice') return '🎤 Voice message';
  if (type === 'image') return text ? `📷 ${text.slice(0, 110)}` : '📷 Photo';
  return text.slice(0, 120);
}
