import { Schema, model, type HydratedDocument, type InferSchemaType } from 'mongoose';

export const MESSAGE_TYPES = ['text', 'voice', 'image'] as const;
export type MessageType = (typeof MESSAGE_TYPES)[number];

// The file behind a voice/image message. The file itself is on disk (uploads/<key>) and is only
// ever served through GET /api/media/:messageId, which checks conversation membership.
const mediaSchema = new Schema(
  {
    key: { type: String, required: true }, // e.g. "images/2026/09/<uuid>.webp"
    mimeType: { type: String, required: true },
    size: { type: Number, required: true }, // bytes
    durationMs: { type: Number }, // voice
    waveform: { type: [Number], default: undefined }, // voice: ~48 bars, each 0..1
    width: { type: Number }, // image
    height: { type: Number }, // image
  },
  { _id: false },
);

const messageSchema = new Schema(
  {
    conversation: { type: Schema.Types.ObjectId, ref: 'Conversation', required: true },
    sender: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    type: { type: String, enum: MESSAGE_TYPES, default: 'text' },
    text: { type: String, trim: true, maxlength: 4000, default: '' }, // message, or photo caption
    media: { type: mediaSchema, default: null },
    // Random id generated by the sender's device. Lets the client match its optimistic bubble to the
    // saved message, and makes retries safe: sending the same clientId twice never creates a duplicate.
    clientId: { type: String, maxlength: 64 },
    editedAt: { type: Date, default: null },
    deletedAt: { type: Date, default: null },
  },
  { timestamps: true },
);

// History pagination: newest first within a conversation (ObjectIds sort by creation time).
messageSchema.index({ conversation: 1, _id: -1 });
messageSchema.index({ sender: 1, clientId: 1 }, { unique: true, partialFilterExpression: { clientId: { $type: 'string' } } });

export type MessageDoc = HydratedDocument<InferSchemaType<typeof messageSchema>>;

export const Message = model('Message', messageSchema);

export function toPublicMessage(m: MessageDoc) {
  const id = m._id.toString();
  const media =
    m.media && !m.deletedAt
      ? {
          url: `/api/media/${id}`,
          mimeType: m.media.mimeType,
          size: m.media.size,
          durationMs: m.media.durationMs ?? null,
          waveform: m.media.waveform ?? null,
          width: m.media.width ?? null,
          height: m.media.height ?? null,
        }
      : null;

  return {
    id,
    conversationId: m.conversation.toString(),
    senderId: m.sender.toString(),
    type: m.type,
    text: m.deletedAt ? '' : m.text,
    media,
    clientId: m.clientId ?? null,
    createdAt: m.createdAt,
    editedAt: m.editedAt ?? null,
    deletedAt: m.deletedAt ?? null,
  };
}

export type PublicMessage = ReturnType<typeof toPublicMessage>;

// Short text for the chat list and notifications.
export function previewFor(type: string, text: string): string {
  if (type === 'voice') return '🎤 Voice message';
  if (type === 'image') return text ? `📷 ${text.slice(0, 110)}` : '📷 Photo';
  return text.slice(0, 120);
}
