import { Schema, model, type HydratedDocument, type InferSchemaType } from 'mongoose';

// 'voice' and 'image' arrive in Phase 4.
export const MESSAGE_TYPES = ['text'] as const;

const messageSchema = new Schema(
  {
    conversation: { type: Schema.Types.ObjectId, ref: 'Conversation', required: true },
    sender: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    type: { type: String, enum: MESSAGE_TYPES, default: 'text' },
    text: { type: String, trim: true, maxlength: 4000, default: '' },
    // Random id generated by the sender's device. Lets the client match its optimistic bubble to the
    // saved message, and makes retries safe: sending the same clientId twice never creates a duplicate.
    clientId: { type: String, maxlength: 64 },
    editedAt: { type: Date, default: null },
    deletedAt: { type: Date, default: null },
  },
  { timestamps: true },
);

// History pagination: newest first within a conversation (ObjectIds sort by creation time).
messageSchema.index({ conversation: 1, _id: -1 });
messageSchema.index({ sender: 1, clientId: 1 }, { unique: true, partialFilterExpression: { clientId: { $type: 'string' } } });

export type MessageDoc = HydratedDocument<InferSchemaType<typeof messageSchema>>;

export const Message = model('Message', messageSchema);

export function toPublicMessage(m: MessageDoc) {
  return {
    id: m._id.toString(),
    conversationId: m.conversation.toString(),
    senderId: m.sender.toString(),
    type: m.type,
    text: m.deletedAt ? '' : m.text,
    clientId: m.clientId ?? null,
    createdAt: m.createdAt,
    editedAt: m.editedAt ?? null,
    deletedAt: m.deletedAt ?? null,
  };
}

export type PublicMessage = ReturnType<typeof toPublicMessage>;
